# -*- coding: utf-8 -*-
"""Final Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BFhNIeqWj38IilsHOtQIZGaFunAjnFgf
"""

 score = 0
score = int(score)

name = input("What is your name?")
name = name.title()
print("""Hello {}, welcome to Global AI Competition! 
You will be presented with 10 questions.
Enter the appropriate number to answer the question
Good luck!""".format(name))

#Question1
print("""WWhat color are avocado?
1. Green
2. Brown 
3. Blue 
4. Pink""")

answer1 = "1"
response1 = input("Your answer is:")

if (response1 != answer1):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response1 + " is correct!")
    score = score + 10

print("Your current score is " + str(score))

#Question2
print("""What is the name of the language that the Elves speak?
1. Sindarin 
2. Elvish 
3. Quenya 
4. Turkish""")

answer2 = "2"
response2 = input("Your answer is:")

if (response2 != answer2):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response2 + " is correct!")
    score = score + 10

print("Your current score is " + str(score))

#Question3
print("""Which team wins the most cups in the Super League?
1. Beşiktaş 
2. Fenerbahçe 
3. Galatasaray 
4. Sakaryaspor""")

answer3 = "3"
response3 = input("Your answer is:")

if (response3 != answer3):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response3 + " is correct!")
    score = score + 10

print("Your current score is " + str(score))

#Question4
print("""Who is 'The Father of Computer Science?
1. Daft Punk
2. Alan Turing
3. Elon Musk
4. Steve Jobs""")

answer4 = "2"
response4 = input("Your answer is:")

if (response4 != answer4):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response4 + " is correct!")
    score = score + 10

print("Your current score is " + str(score))

#Question5
print("""Who is calling 'The Leonardo da Vinci of the 21st Century?
1. Zeus
2. Maroon 5
3. Refik Anadol
4. Noone""")

answer5 = "3"
response5 = input("Your answer is:")

if (response5 != answer5):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response5 + " is correct!")
    score = score + 10

print("Your current score is " + str(score))

#Question6
print("""Who is dumber ?
1. Garfield
2. Peter Griffin 
3. Homer Simpson 
4. Ash""")

answer6 = "3"
response6 = input("Your answer is:")

if (response6 != answer6):
    print("Sorry, for Reddit it's Homer Simpson")
else:
    print("Well done! " + response6 + " is correct!")
    score = score + 10

print("Your current score is " + str(score))

#Question7
print("""The Most Beautiful City?
1. Paris 
2. Istanbul 
3. Tokio 
4. Beirut""")

answer7 = "3"
response7 = input("Your answer is:")

if (response7 != answer7):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response7 + " is correct!")
    score = score + 10

print("Your current score is " + str(score))

#Question8
print("""Best AI initiative
1. Global AI HUB 
2. - 
3. - 
4. -""")

answer8 = "1"
response8 = input("Your answer is:")

if (response8 != answer8):
    print("Sorry, that is incorrect!")
else:
    print("Of course " + response8 + " is correct!")
    score = score + 10

print("Your current score is " + str(score))

#Question9
print("""What is Omer Cengiz spoken the most?
1. Kurumuş boğazım
2. Bugün çok güzel bir gün""")

answer9 = "1","2"
response9 = input("Your answer is:")

if (response9 != answer9):
    print("Sorry, that is incorrect!")
else:
    print("Well done! " + response9 + " is correct!")
    score = score + 10

print("Your current score is " + str(score))

#Question10
print("""Is this the last question?
1. Yes
2. No
3. Maybe
4. Hopefully""")

answer10 = "1"
response10 = input("Your answer is:")

if (response10 != answer10):
    print("Sorry, we don't have anymore question.")
else:
    print("Well done! " + response10 + " is correct!")
    score = score + 10

print("Your total score is " + str(score) + " out of 100")

if (score >= 50):
    print("{} You Win!")
else:
    print("Sorry!, You Lose {} ")
