# -*- coding: utf-8 -*-
"""odev1-gelistirilmisversiyon

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IEm87XF4MJe05UzWVRQewBz_UBV--WKR
"""

print ('Lütfen 4 tane tek ve 4 tane çift sayı giriniz') 

listodd = []
listeven = []
while True:
    print(len(listodd),len(listeven))
    sayi=int(input("bir sayi girin: "))
    if len(listodd) == 4 and len(listeven)==4:
        break
    if sayi not in listodd and sayi not in listeven:
        if sayi % 2 == 0 and len(listeven) != 4:
            listeven.append(sayi)
        elif sayi % 2 != 0 and len(listodd) != 4:
            listodd.append(sayi)
listodd.extend(listeven)
list_new = list (listodd)
print (list_new)

list_new.sort()
print(list_new)

list_new = [x*2 for x in(list_new)]
print (list_new)

for x in list_new:
    print("{} veri tipi: {}".format(x, type(x)))
