# -*- coding: utf-8 -*-
"""hw2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QmpXlwvCHLuRQ1_mfO_LlX20VMXen205
"""

cv1 = {"AdSoyad": "Ahmet Bir", "Telefon Numarası": "5133311122", "Mesleği": "Öğretmen"}
cv2 = {"AdSoyad": "Ahmet İki", "Telefon Numarası": "5233311122", "Mesleği": "Yazılımcı"}
cv3 = {"AdSoyad": "Ahmet Üç", "Telefon Numarası": "5333311122", "Mesleği": "Tasarımcı"}
cv4 = {"AdSoyad": "Ahmet Dört", "Telefon Numarası": "5433311122", "Mesleği": "Mühendis"}
cv5 = {"AdSoyad": "Ahmet Beş", "Telefon Numarası": "5533311122", "Mesleği": "İşsiz"}


print (cv1)
print (cv2)
print (cv3)
print (cv4)
print (cv5)

type(cv1) 
type(cv2) 
type(cv3) 
type(cv4) 
type(cv5)

