# -*- coding: utf-8 -*-
"""hw3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IimoKJuRYB6hLKsguGyC5B8COvfNqFmK
"""

stu1 = input("1.Ogrencinin adini giriniz:")
stu1Not =()

print("1. Ogrencinin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

stu1Not=(result)
print(stu1,":" ,stu1Not)

stu2 = input("2.Ogrencinin Adini Giriniz:")
stu2Not = ()
print("2. Ogrenci'nin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

stu2Not=(result)

print(stu2,":" ,stu2Not)

stu3 = input("3.Ogrencinin adini giriniz:")
stu3Not =()
print("3. Ogrencinin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

stu3Not=(result)

print(stu3,":" ,stu3Not)

stu4 = input("4.Ogrencinin Adini Giriniz:")
stu4Not = ()
print("4. Ogrenci'nin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

stu4Not=(result)

print(stu4,":" ,stu4Not)

stu5 = input("5.Ogrencinin Adini Giriniz:")
stu5Not = ()
print("5. Ogrenci'nin Notlarini Girer misiniz ?")

MidtermGrade = int(input("MidtermGrade :"))
Project = int(input("Project :"))
FinalGrade = int(input("Final Grade :"))
result = (MidtermGrade*0.3) + (Project*0.3) + (FinalGrade*0.4)

stu5Not=(result)
print(stu5,":" ,stu5Not)

Ogrenci = {stu1 : stu1Not, stu2 : stu2Not, stu3 : stu3Not, stu4 : stu4Not, stu5 : stu5Not}
{k: v for k, v in sorted(Ogrenci.items(), key=lambda item: item[1])}

print (Ogrenci)
type (Ogrenci)

